from ..Filter import Filter


class Industry(Filter):
    prefix: str = "ind"
    values: dict = {
        "stocksonly": "Stocks only (ex-Funds)",
        "exchangetradedfund": "Exchange Traded Fund",
        "advertisingagencies": "Advertising Agencies",
        "aerospacedefense": "Aerospace & Defense",
        "agriculturalinputs": "Agricultural Inputs",
        "airlines": "Airlines",
        "airportsairservices": "Airports & Air Services",
        "aluminum": "Aluminum",
        "apparelmanufacturing": "Apparel Manufacturing",
        "apparelretail": "Apparel Retail",
        "assetmanagement": "Asset Management",
        "automanufacturers": "Auto Manufacturers",
        "autoparts": "Auto Parts",
        "autotruckdealerships": "Auto & Truck Dealerships",
        "banksdiversified": "Banks - Diversified",
        "banksregional": "Banks - Regional",
        "beveragesbrewers": "Beverages - Brewers",
        "beveragesnonalcoholic": "Beverages - Non-Alcoholic",
        "biotechnology": "Biotechnology",
        "broadcasting": "Broadcasting",
        "buildingmaterials": "Building Materials",
        "buildingproductsequipment": "Building Products & Equipment",
        "businessequipmentsupplies": "Business Equipment & Supplies",
        "capitalmarkets": "Capital Markets",
        "chemicals": "Chemicals",
        "closedendfunddebt": "Closed-End Fund - Debt",
        "closedendfundequity": "Closed-End Fund - Equity",
        "closedendfundforeign": "Closed-End Fund - Foreign",
        "cokingcoal": "Coking Coal",
        "communicationequipment": "Communication Equipment",
        "computerhardware": "Computer Hardware",
        "confectioners": "Confectioners",
        "conglomerates": "Conglomerates",
        "consultingservices": "Consulting Services",
        "consumerelectronics": "Consumer Electronics",
        "copper": "Copper",
        "creditservices": "Credit Services",
        "departmentstores": "Department Stores",
        "diagnosticsresearch": "Diagnostics & Research",
        "discountstores": "Discount Stores",
        "drugmanufacturersgeneral": "Drug Manufacturers - General",
        "educationtrainingservices": "Education & Training Services",
        "electricalequipmentparts": "Electrical Equipment & Parts",
        "electroniccomponents": "Electronic Components",
        "electronicgamingmultimedia": "Electronic Gaming & Multimedia",
        "engineeringconstruction": "Engineering & Construction",
        "entertainment": "Entertainment",
        "farmproducts": "Farm Products",
        "financialconglomerates": "Financial Conglomerates",
        "fooddistribution": "Food Distribution",
        "footwearaccessories": "Footwear & Accessories",
        "gambling": "Gambling",
        "gold": "Gold",
        "grocerystores": "Grocery Stores",
        "healthcareplans": "Healthcare Plans",
        "healthinformationservices": "Health Information Services",
        "homeimprovementretail": "Home Improvement Retail",
        "householdpersonalproducts": "Household & Personal Products",
        "industrialdistribution": "Industrial Distribution",
        "informationtechnologyservices": "Information Technology Services",
        "infrastructureoperations": "Infrastructure Operations",
        "insurancebrokers": "Insurance Brokers",
        "insurancediversified": "Insurance - Diversified",
        "insurancelife": "Insurance - Life",
        "insurancepropertycasualty": "Insurance - Property & Casualty",
        "insurancereinsurance": "Insurance - Reinsurance",
        "insurancespecialty": "Insurance - Specialty",
        "integratedfreightlogistics": "Integrated Freight & Logistics",
        "internetcontentinformation": "Internet Content & Information",
        "internetretail": "Internet Retail",
        "leisure": "Leisure",
        "lodging": "Lodging",
        "lumberwoodproduction": "Lumber & Wood Production",
        "luxurygoods": "Luxury Goods",
        "marineshipping": "Marine Shipping",
        "medicalcarefacilities": "Medical Care Facilities",
        "medicaldevices": "Medical Devices",
        "medicaldistribution": "Medical Distribution",
        "medicalinstrumentssupplies": "Medical Instruments & Supplies",
        "metalfabrication": "Metal Fabrication",
        "mortgagefinance": "Mortgage Finance",
        "oilgasdrilling": "Oil & Gas Drilling",
        "oilgasep": "Oil & Gas E&P",
        "oilgasequipmentservices": "Oil & Gas Equipment & Services",
        "oilgasintegrated": "Oil & Gas Integrated",
        "oilgasmidstream": "Oil & Gas Midstream",
        "oilgasrefiningmarketing": "Oil & Gas Refining & Marketing",
        "otherindustrialmetalsmining": "Other Industrial Metals & Mining",
        "otherpreciousmetalsmining": "Other Precious Metals & Mining",
        "packagedfoods": "Packaged Foods",
        "packagingcontainers": "Packaging & Containers",
        "paperpaperproducts": "Paper & Paper Products",
        "personalservices": "Personal Services",
        "pharmaceuticalretailers": "Pharmaceutical Retailers",
        "pollutiontreatmentcontrols": "Pollution & Treatment Controls",
        "publishing": "Publishing",
        "railroads": "Railroads",
        "realestatedevelopment": "Real Estate - Development",
        "realestatediversified": "Real Estate - Diversified",
        "realestateservices": "Real Estate Services",
        "recreationalvehicles": "Recreational Vehicles",
        "reitdiversified": "REIT - Diversified",
        "reithealthcarefacilities": "REIT - Healthcare Facilities",
        "reithotelmotel": "REIT - Hotel & Motel",
        "reitindustrial": "REIT - Industrial",
        "reitmortgage": "REIT - Mortgage",
        "reitoffice": "REIT - Office",
        "reitresidential": "REIT - Residential",
        "reitretail": "REIT - Retail",
        "reitspecialty": "REIT - Specialty",
        "rentalleasingservices": "Rental & Leasing Services",
        "residentialconstruction": "Residential Construction",
        "resortscasinos": "Resorts & Casinos",
        "restaurants": "Restaurants",
        "scientifictechnicalinstruments": "Scientific & Technical Instruments",
        "securityprotectionservices": "Security & Protection Services",
        "semiconductors": "Semiconductors",
        "shellcompanies": "Shell Companies",
        "silver": "Silver",
        "softwareapplication": "Software - Application",
        "softwareinfrastructure": "Software - Infrastructure",
        "solar": "Solar",
        "specialtybusinessservices": "Specialty Business Services",
        "specialtychemicals": "Specialty Chemicals",
        "specialtyindustrialmachinery": "Specialty Industrial Machinery",
        "specialtyretail": "Specialty Retail",
        "staffingemploymentservices": "Staffing & Employment Services",
        "steel": "Steel",
        "telecomservices": "Telecom Services",
        "textilemanufacturing": "Textile Manufacturing",
        "thermalcoal": "Thermal Coal",
        "tobacco": "Tobacco",
        "toolsaccessories": "Tools & Accessories",
        "travelservices": "Travel Services",
        "trucking": "Trucking",
        "uranium": "Uranium",
        "utilitiesdiversified": "Utilities - Diversified",
        "utilitiesregulatedelectric": "Utilities - Regulated Electric",
        "utilitiesregulatedgas": "Utilities - Regulated Gas",
        "utilitiesregulatedwater": "Utilities - Regulated Water",
        "utilitiesrenewable": "Utilities - Renewable",
        "wastemanagement": "Waste Management",
    }
